name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # Validate release
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ -v --tb=short
    
    - name: Check documentation
      run: |
        # Verify all documentation files exist
        test -f README.md
        test -f docs/README.md
        test -f docs/getting-started.md
        test -f docs/user-guide.md
        test -f docs/configuration.md
        test -f docs/cli-reference.md
        test -f docs/plugin-development.md
        test -f docs/api-reference.md
        test -f docs/installation.md
        test -f docs/monitoring.md
        echo "✓ All documentation files present"
    
    - name: Validate package metadata
      run: |
        python -c "
        import santiq
        print(f'Package version: {santiq.__version__}')
        print(f'Package author: {santiq.__author__}')
        print(f'Package email: {santiq.__email__}')
        "
    
    - name: Test CLI installation
      run: |
        python -m santiq.cli.main --version
        python -m santiq.cli.main --help

  # Build and publish
  release:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package contents
      run: |
        tar -tzf dist/*.tar.gz | head -20
        echo "Package contents verified"
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        # Upload to PyPI
        twine upload dist/*
        echo "✓ Package published to PyPI"
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        draft: false
        prerelease: false
        title: Release ${{ github.ref_name }}
        body: |
          ## 🚀 Santiq ${{ github.ref_name }}
          
          ### 📦 What's New
          - Enhanced ETL pipeline capabilities
          - Improved plugin system
          - Comprehensive documentation
          - Better error handling and monitoring
          
          ### 📚 Documentation
          - [Getting Started Guide](https://github.com/${{ github.repository }}/blob/main/docs/getting-started.md)
          - [User Guide](https://github.com/${{ github.repository }}/blob/main/docs/user-guide.md)
          - [API Reference](https://github.com/${{ github.repository }}/blob/main/docs/api-reference.md)
          
          ### 🔧 Installation
          ```bash
          pip install santiq
          ```
          
          ### 📋 Changelog
          See the [full changelog](https://github.com/${{ github.repository }}/commits/main) for detailed changes.
